server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://39.107.235.107:3306/loser?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Li081206!
    driver-class-name: com.mysql.cj.jdbc.Driver
