server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://39.107.235.107:3306/loser?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Li081206!
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0  # Redis数据库索引（默认为0）
    host: 39.107.235.107 # Redis服务器地址
    port: 6379  # Redis服务器连接端口
    password: Li081206!  # Redis服务器连接密码（默认为空）
    lettuce:
      pool:
       max-active: 8  # 连接池最大连接数（使用负值表示没有限制） 默认 8
       max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
       max-idle: 8    # 连接池中的最大空闲连接 默认 8
       min-idle: 0    # 连接池中的最小空闲连接 默认 0

