server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://mysql-cn-north-1-864635669a4f4295.rds.jdcloud.com:3358/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: smart_ddl
    password: GDe7MmJd405jR75f6oDFHlnlp3wjXPJv
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    ##控制台打印sql
    show-sql: true
    open-in-view: true