server:
  port: 9001

spring:
  application:
    name: loser-provider
  cloud:
    nacos:
      discovery:
        server-addr: 39.107.235.107:8848 #配置Nacos地址
  cache:
    redis:
      ## Entry expiration in milliseconds. By default the entries never expire.
      time-to-live: 1d
      #写入redis时是否使用键前缀。
      use-key-prefix: true

management:
  endpoints:
    web:
      exposure:
        include: '*'


