server:
  port: 9001

spring:
  application:
    name: loser-provider
  cloud:
    nacos:
      discovery:
        server-addr: 39.107.235.107:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'


